=== mutanthost/backupEC2/ORACLE_19/suptools/orachk/user_defined_checks.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="UserDefinedChecks">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="CHECK" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="DISABLED" type="xs:string" minOccurs="0"/>
							<xs:element name="ORACLE_VERSION" type="xs:string"/>
							<xs:element name="PLATFORMS">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="PLATFORM" maxOccurs="unbounded" minOccurs="0"> 
											<xs:complexType>
												<xs:sequence>
													<xs:element name="FLAVOR" type="xs:string" minOccurs="0"/> 
												</xs:sequence>
												<xs:attribute name="TYPE" type="xs:string"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="OS_COMMAND" type="xs:string" minOccurs="0"/>
							<xs:element name="OS_COMMAND_REPORT" type="xs:string" minOccurs="0"/>
                                                        <xs:element name="OS_REPAIR_COMMAND" type="xs:string" minOccurs="0"/>
							<xs:element name="PARAM_PATH" type="xs:string" minOccurs="0"/>
							<xs:element name="SQL_COMMAND" type="xs:string" minOccurs="0"/>
							<xs:element name="SQL_COMMAND_REPORT" type="xs:string" minOccurs="0"/>
                                                        <xs:element name="SQL_REPAIR_COMMAND" type="xs:string" minOccurs="0"/>
							<xs:element name="OPERATOR" type="xs:string"/>
                                                        <xs:element name="COMPARE_VALUE" type="xs:string" minOccurs="0"/>
							<xs:element name="CHECK_TIMEOUT" type="xs:string" minOccurs="0"/>
                                                        <xs:element name="CANDIDATE_SYSTEMS" type="xs:string"/>
                                                        <xs:element name="COMPONENT_DEPENDENCY" type="xs:string" minOccurs="0"/>
                                                        <xs:element name="DATABASE_MODE" type="xs:string" minOccurs="0"/>
							<xs:element name="ORACLE_HOME_TYPE" type="xs:string" minOccurs="0"/>
							<xs:element name="DATABASE_TYPE" type="xs:string" minOccurs="0"/>
							<xs:element name="DATABASE_ROLE" type="xs:string" minOccurs="0"/>
							<xs:element name="ALERT_LEVEL" type="xs:string"/>
							<xs:element name="PASS_MSG" type="xs:string"/>
							<xs:element name="FAIL_MSG" type="xs:string"/>
							<xs:element name="BENEFIT_IMPACT" type="xs:string" minOccurs="0"/>
							<xs:element name="RISK" type="xs:string" minOccurs="0"/>
							<xs:element name="ACTION_REPAIR" type="xs:string" minOccurs="0"/>
							<xs:element name="LINKS" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="LINK" maxOccurs="unbounded" type="xs:string"/> 
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="AUDIT_CHECK_NAME" type="xs:string"/>
					</xs:complexType>
				</xs:element> 
			</xs:sequence>
		</xs:complexType>
	</xs:element> 
</xs:schema>

=== mutanthost/backupEC2/ORACLE_19/suptools/orachk/sample_user_defined_checks.xml
<?xml version="1.0" encoding="UTF-8"?>

<UserDefinedChecks
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="user_defined_checks.xsd"> <!-- Main Tag (root element)-->


<!-- +++++ USER DEFINED CHECKS +++++ -->

<!-- This is a SAMPLE file containing example checks for OS and SQL Checks -->
<!-- DO NOT EDIT this file and use it for your user defined checks.  Make a COPY of this file and save as user_defined_checks.xml -->
<!-- Create a new blank user_defined_checks.xml file using vi and copy the header above the +++++USER DEFINED CHECKS +++++ comment above -->
<!-- and the closing tag </UserDefinedChecks> at the very end of this file.  Your checks will be between the header and the closing tag -->
<!-- Use the sample checks below as templates and copy/paste/edit them in user_defined_checks.xml -->
<!-- Use your own checks as templates for other checks that you create -->
<!-- Checks are enclosed by <CHECK AUDIT_CHECK_NAME= ... and </CHECK> -->

<!-- This sample file is intended only for instructions and to copy sample checks to use as a template for your checks -->
<!-- The idea is to provide the values and logic that apply to your environment in your own -->

<!-- Most customers will have one or two platforms and one or two versions in there environment -->

<!-- +++++ TIPS AND TECHNIQUES +++++ -->

<!-- 1.   For best results use the vi editor.  Other editors may substitute characters that are not interpreted well in XML -->
<!-- 2.   DO NOT change the order of the XML tags.  A few tags can be removed when not applicable as noted below -->
<!-- 3.   Certain special characters must be substituted in order to be properly interpreted in XML,e.g.. -->
<!--        && should be &amp;&amp; 	-->
<!--        >= should be &gt; 		-->
<!--         <= should be &lt; 		-->
<!--        etc.		 		-->
<!-- 4.   Some editors will substitute other characters for single and double quote characters.  Make sure only plain single and double quotes are used  -->
<!-- 5.   By default ORAchk will run checks it finds in user_defined_checks.xml if the file exists.  To substitute a different file you may set RAT_USER_DEFINED_CHECKS -->
<!--        To substitute a different file you may set RAT_USER_DEFINED_CHECKS to point to the alternate file but it must be a valid user defined checks XML file -->
<!-- 6.   To run ONLY the user defined checks you may use the special built-in profile user_defined_checks, e.g.. -->
<!--        $ ./orachk -profile user_defined_checks 	-->
<!--        This will skip all other checks and only run the user defined checks -->
<!-- 7.   Running user defined checks as root is not supported -->
<!-- 8.   When ORAchk is upgraded this sample file will be over-written but the user_defined_checks.xml will NOT be over-written -->
<!-- 9.   Keep a backup copy of user_defined_checks.xml each time it is edited to maintain a fallback copy in case of loss or mistakes in editing -->
<!-- 10.  SQL commands can be embedded in OS commands. OS commands can consist of single-line programs as in the OSW Watcher Retention Check example below -->
<!-- 11.  Oracle Support is not responsible for your checks.  You must devise your own logic.  This mechanism only provides you with a method of automating your own checks  -->


<!-- OS AUDIT CHECK NAME -->
<!-- Use a name that is self documenting, enclosing the name in double quotes -->

<!-- +++++ BEGIN NEW OS CHECK +++++ -->

<CHECK AUDIT_CHECK_NAME="ASM Audit File Directory Growth">

<!-- SUPPORTED VERSIONS -->
<!-- The following VERSIONS are supported for Grid Infrastructure and Database -->
<!-- Remove any versions not present in your environment and any that your check does not apply to -->
<!-- If your check applies to multiple supported versions then include them in this list  -->
<!-- Your checks will only run on the version or versions that you specify and sometimes the logic for a check will be version-specific  -->
<!-- It doesnâ€™t hurt anything to specify versions that do not exist in your environment  -->
<!-- Versions that do not exist in your environment will just be ignored.  On the other hand, if a check is version-specific then you   -->
<!-- would want to remove the versions that the check does not apply to.  -->

<!-- All versions                                         -->
	<ORACLE_VERSION>*</ORACLE_VERSION> 

<!--  Other valid alternative version specifications      -->

<!-- 		<ORACLE_VERSION>112040</ORACLE_VERSION> would be an example for a check that is specific to 11.2.0.4 -->
<!--		<ORACLE_VERSION>102040:102050:111070:112010:112020:112030:112040:121010:121020</ORACLE_VERSION>      -->

<!-- SUPPORTED PLATFORMS -->
<!-- The following PLATFORMS are supported -->
<!-- Remove any platforms that are not present in your environment or for which your check does not apply -->
<!-- Each platform has one or more "flavors", which are distributions or versions which vary from platform to platform  -->
<!-- Many OS checks might be platform specific so those should be limited to the proper platforms  -->
<!-- For Linux OELRHEL refers to Oracle Linux or Red Hat Linux  -->
<!-- If removing platforms remove everything from the <PLATFORM> to </PLATFORM> tags leaving only the platforms you need  -->

<!--  All platforms and flavors using "*" wildcard   -->
    <PLATFORMS>
    <PLATFORM TYPE="*">
      <FLAVOR>*</FLAVOR>
    </PLATFORM>
    </PLATFORMS>


<!--  Other valid Platform specifications which can be sued depending upon your platform            -->
<!--		<PLATFORMS>                                                                         -->
<!--			<PLATFORM TYPE="LINUXX8664">                                                -->
<!--				<FLAVOR>OELRHEL5:OELRHEL6:OELRHEL7:SUSE10:SUSE11:SUSE12</FLAVOR>    -->
<!--			</PLATFORM>                                                                 -->
<!--			<PLATFORM TYPE="SOLARISSPARC64">                                            -->
<!--				<FLAVOR>10:11</FLAVOR>                                              -->
<!--			</PLATFORM>                                                                 -->
<!--			<PLATFORM TYPE="SOLARISX8664">                                              -->
<!--                            <FLAVOR>10:11</FLAVOR>                                              -->
<!--                    </PLATFORM>                                                                 -->
<!--			<PLATFORM TYPE="AIXPPC64">                                                  -->
<!--				<FLAVOR>61:71</FLAVOR>                                              -->
<!--			</PLATFORM>                                                                 -->
<!--			<PLATFORM TYPE="MSWINDOWS">                                                 -->
<!--                            <FLAVOR>64</FLAVOR>                                                 -->
<!--                    </PLATFORM>                                                                 -->
<!--			<PLATFORM TYPE="HPUX">                                                      -->
<!--                                <FLAVOR>Itanium1131</FLAVOR>                                    -->
<!--                        </PLATFORM>                                                             -->
<!--			<PLATFORM TYPE="HPUX">                                                      -->
<!--                                <FLAVOR>PARISC1123</FLAVOR>                                     -->
<!--                        </PLATFORM>                                                             -->
<!--		</PLATFORMS>                                                                        -->

<!-- If for instance you only have 64-bit OEL5 in your environment then your platform block for your checks could be as follows -->

<!--		<PLATFORMS> 					              -->
<!--			<PLATFORM TYPE="LINUXX8664"> 		              -->
<!--				<FLAVOR>OELRHEL5</FLAVOR>	              -->
<!--			</PLATFORM>				              -->
<!--            </PLATFORMS>                                                  -->

<!--            <PLATFORMS>                                                   -->
<!--            <PLATFORM TYPE="LINUXX8664">   for Linux and all flavors      -->
<!--            <FLAVOR>*</FLAVOR>                                            -->
<!--            </PLATFORM>                                                   -->
<!--            </PLATFORMS>                                                  -->

<!-- OS COMMAND CHECK LOGIC -->
<!-- This command or inline program should result in a single string or numeric return value that can be compared to a single comparison value -->
<!-- using an appropriate string or numeric comparison operator.  Typically this will be a boolean return value like in the sample below, 1 or 0 -->
<!-- But it could be a count resulting from the use of a command like grep -c where the count is expected to be 0 or a non-zero number  -->
<!-- depending upon the logic required for your check.  The important thing to remember though is that it should not result in a list or array -->
<!-- The best approach is to perfect your logic in a terminal shell and once perfected copy and paste it into the OS_COMMAND block of your check -->
<!-- Note that ORAchk populates two environment variables at runtime $CRS_HOME and $ORACLE_HOME.  So you can use those in you logic as in the example -->
<!-- $CRS_HOME will be static but $ORACLE_HOME will change according to the context of its usage which is defined by ORACLE_HOME_TYPE below -->
<!-- Note that when querying v$ views in Oracle using OS commands like this the dollar sign needs to be escaped as in v\$parameter -->
<!-- Note also that it is possible to embed SQLPlus formatting directives in your command and that a newline character (\n) follows them  -->
<!-- In this form of a multi-command program preceding tabs will cause problems so do not use any  -->
<!-- NOTE: NO tabs embedded in multi-line program -->

	<OS_COMMAND> 
	<![CDATA[
